# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 889b87e84658451848866ff1d1256da3d276da1f8f4eddc2e6f28b5aaf5e75aa9cace381fbe2514c05666c38fb56ad6d53ed172e4abd2a6b25987d27a3ba575a

test:
  secret_key_base: 8e398e14c993c1bbe92b5fcbb6f26a43a8017d30fb506989b3c16e26e86b6ccdb596b3a469fc67ae47b84c35d83f1a4aa4fa5daefba9892e448ad920efe4714a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
